version: '3.9'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./dev:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
    volumes_from:
      - php
    depends_on:
      - php
      - mysql
    networks:
      - laravel
    
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'homestead'
      MYSQL_USER: 'homestead'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
      SERVICE_TAGS: 'dev'
      SERVICE_NAME: 'mysql'
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    ports:
      - '8001:80'
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
    networks:
      - laravel
    

  php:
    image: php:8-fpm
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./dev:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel